spring.application.name=validador-documentos

spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB

spring.ai.model.chat=openai
spring.ai.model.embedding=none
spring.ai.model.image=none
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none
spring.ai.model.moderation=none
spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.chat.model=gpt-5-mini
